# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{has_dynamic_attribute}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tim.teng"]
  s.date = %q{2010-08-25}
  s.description = %q{build dynamic attributes at instance level, saved in database with json format}
  s.email = %q{tim.rubist@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "has_dynamic_attribute.gemspec",
     "lib/has_dynamic_attribute.rb",
     "lib/hda/ar_accessors.rb",
     "lib/hda/av_form_helpers.rb",
     "test/helper.rb",
     "test/test_has_dynamic_attribute.rb"
  ]
  s.homepage = %q{http://github.com/tteng/has_dynamic_attribute}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{build dynamic attributes at instance level}
  s.test_files = [
    "test/test_has_dynamic_attribute.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<json>, [">= 1.4.6"])
      s.add_development_dependency(%q<json_pure>, [">= 1.2.2"])
    else
      s.add_dependency(%q<json>, [">= 1.4.6"])
      s.add_dependency(%q<json_pure>, [">= 1.2.2"])
    end
  else
    s.add_dependency(%q<json>, [">= 1.4.6"])
    s.add_dependency(%q<json_pure>, [">= 1.2.2"])
  end
end

